# Number of days of inactivity before an issue becomes stale
daysUntilStale: 400
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 400

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - bug

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. Please comment here if it is still valid so that we can
  reprioritize. Thank you!

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  Closing this. Please reopen if you believe it should be addressed. Thank you for your contribution.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 10
